Add option to copy source packages out of the container

diff --git a/buildbin b/buildbin
--- a/buildbin
+++ b/buildbin
@@ -69,6 +69,7 @@ while [[ -n "$1" ]]; do
                        fi
                        setpath srcdir[1] "$1"                                 ;;
     -t|--chroot)       shift; chroot=1; setpath rootdir "$1"                  ;;
+    -p|--copy-src)     shift; copysrc=1; setpath spkgdir "$1"                 ;;
     -l|--launch)       true                                                   ;;
        --force-reset)  freset=1                                               ;;
        --)             shift; commands=( "$@" ); break                        ;;
@@ -109,6 +110,7 @@ Options:
                           and second the mountpoint within the chroot
   -m, --makedir           make build directory if it does not exist
   -c, --copy              copy packages to the system pacman cache
+  -p, --copy-src          copy source packages to the specified directory
   -i, --install           install all packages that were built. implies --copy
   -r, --repo <database>   add packages to a local repository. specify by path or
                           by name
@@ -197,6 +199,7 @@ fi
 [[ -z $chroot || -d "$rootdir" ]] || die 4 "chroot path ${rootdir/${rootdir}/${rootdir} }not found. exiting."
 [[ -x "$rootdir"/bin/bash ]]      || die 5 "linux installation not present at $rootdir/. exiting."
 [[ -n $homedir ]]                 || die 6 "user $chuser not found. exiting."
+[[ -z $copysrc || -d "$spkgdir" ]] || die 17 "source package directory ${spkgdir/${spkgdir}/${spkgdir} }not found. exiting."
 
 # Reset the build folder
 function resetbuild {
@@ -374,7 +377,16 @@ sed -ni '/### Generated by buildbin. Do not write below this line. ###/q;p' "$me
 
 ### After exiting chroot, organize packages if requested #######################
 
-if ((! copy)) && ((! repo)) && ((! install)); then
+# Generate search criteria or exit if not saving work
+if ((copy)) || ((repo)) || ((install)); then
+  if ((copysrc)); then
+    regex='src|pkg'
+  else
+    regex='pkg'
+  fi
+elif ((copysrc)); then
+  regex='src'
+else
   exit 0
 fi
 echo
@@ -390,23 +402,24 @@ if ((copy)); then
       *.sig) copysigs+=( "$line" ) ;;
       *)     tocopy+=( "$line" )   ;;
     esac
-  done < <(find "${upperdir}_"* 2>/dev/null "${prune[@]}" -newerct @$time -type f -name '*.pkg.tar*' -print0)
+  done < <(find "${upperdir}_"* 2>/dev/null "${prune[@]}" -newerct @$time -type f -regextype posix-extended -regex '(.+-){3}.+\.pkg\.tar.*' -print0)
 fi
 
 # Now search the source directory
 while IFS= read -r -d '' line; do
   case "$line" in
-    *.sig) signatures+=( "$line" ) ;;
-    *)     toinstall+=( "$line" )  ;;
+    *pkg.tar*.sig) signatures+=( "$line" ) ;;
+    *pkg.tar*)     toinstall+=( "$line" )  ;;
+    *src.tar*)     tocopysrc+=( "$line" )  ;;
   esac
-done < <(find "$mergedir${srcdir[1]}" 2>/dev/null -newerct @$time -type f -name '*.pkg.tar*' -print0)
+done < <(find "$mergedir${srcdir[1]}" 2>/dev/null -newerct @$time -type f -regextype posix-extended -regex '(.+-){3}.+\.('$regex')\.tar.*' -print0)
 
 # Print search summary
-if [[ -z "${tocopy[0]}" && -z "${toinstall[0]}" ]]; then
+if [[ -z "${tocopy[0]}" && -z "${toinstall[0]}" && -z "${tocopysrc[0]}" ]]; then
   echo "none found."
   exit 0
 else
-  echo "$((${#tocopy[@]}+${#toinstall[@]})) found."
+  echo "$((${#tocopy[@]}+${#toinstall[@]}+${#tocopysrc[@]})) found."
   echo
 fi
 
@@ -422,14 +435,19 @@ if ((copy)) || ((repo)); then
 fi
 
 # Perform the relevant actions on the files
+if ((copysrc)); then
+  [[ -z ${tocopysrc[0]} ]] || cp -uv --backup=numbered --target-directory="$spkgdir" "${tocopysrc[@]}"
+fi
+
 if ((copy)); then
-  cp -uv "${tocopy[@]}" "${copysigs[@]}" "${toinstall[@]}" "${signatures[@]}" "$cachedir"/
+  [[ -z ${tocopy[0]} ]] || cp -uv --target-directory="$cachedir" "${tocopy[@]}" "${copysigs[@]}"
+  [[ -z ${toinstall[0]} ]] || cp -uv --target-directory="$cachedir" "${toinstall[@]}" "${signatures[@]}"
 fi
 
 if [[ -n ${toinstall[0]} ]]; then
   if ((repo)); then
     if ((! copy)) || [[ ! "$repodir" -ef "$cachedir" ]]; then
-      cp -uv "${toinstall[@]}" "${signatures[@]}" "$repodir"/
+      cp -uv --target-directory="$repodir" "${toinstall[@]}" "${signatures[@]}"
     fi
     /usr/bin/repo-add "$repodb" "${toinstall[@]/*\//$repodir/}"
   fi
